version: '3.7'

name: myproject

services:
  app:
    container_name: App
    image: ${APP_IMAGE_PATH}
    restart: unless-stopped
    ports: 
      - 3000:3000
    mem_limit: '400m'
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
  
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    platform: linux/x86_64
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development
    ports:
      - 3307:3306
    volumes:
      - dev_env_mysql_data:/var/lib/mysql

volumes:
  dev_env_mysql_data: {}

